### ISSUE TITLE
"LODE error"

### ISSUE THREAD

**Issue by akuckartz** [argu-co/popolo-ori#1]
This link in the README
"Auto-generated documentation which includes Popolo."
http://www.essepuntato.it/lode/imported/reasoner/https://raw.githubusercontent.com/argu-co/popolo-ori/master/popolo-ext.owl
results in this error:
```
LODE error
Reason: https://raw.githubusercontent.com/argu-co/popolo-ori/master/popolo-ext.owl
```

**Comment by akuckartz** [comment]
This works:
http://www.essepuntato.it/lode/https://raw.githubusercontent.com/argu-co/popolo-ori/master/popolo-ori.owl

**Comment by joepio** [comment]
Thanks! Updated it :)
